### PR TITLE
Major refactor of argument parsing

### PR DESCRIPTION
**Pull request by alex-davidson**
* Redesign argument parsing, based on experience acquired since this library was originally written.
* Use the standard free-threaded async pattern by default for console apps.
* Factor out the Formatting namespace, since it's rarely used.
* Redesign logging policies and the manner in which they are initialised.

Bluewire.Common.Console: 10.2.1 -> 11.0.0

### CODE REVIEW

**Comment by alex-davidson** [comment]
This should probably incorporate CC-16 too: addition of opinionated logging by default.

**Review by markboyall — DISMISSED** [review]

**Comment by alex-davidson** [comment]
I would mark this as 'Blocked' but we have no label for that in this repo.

**Comment by emmaffiondavies** [comment]
> @alex-davidson: _"I would mark this as 'Blocked' but we have no label for that in this repo."_

Done :)

**Comment by alex-davidson** [comment]
This is almost ready to go, but requires some testing against existing consumer projects first.

**Comment by alex-davidson** [comment]
The logging reimplementation adds first-class support for log folder configuration via AppSettings. However, it uses a fixed config key. Does OctopusDeploy let us easily assign different values to a given AppSetting key for each package?

**Comment by alex-davidson** [comment]
The answer is no, it doesn't.

Further changes needed here:
* must ignore empty values in AppSettings because Octopus will need the key present in order to replace something *sigh*
* must prefer an `<appname>:LogDirectory` key (or whatever) if present, so we can set this per-application. Means knowing the appname in the config code...

**Comment by alex-davidson** [comment]
This is completed as far as I know, and there exists a branch in the Epro repository against which it has been tested.

**Review by markboyall — APPROVED** [review]

**Pull request merged**
